### ISSUE TITLE
TMDB内容获取错误

### ISSUE THREAD

**Issue by haig233** [ccf-2012/torcp#13]
```
=========>>> 2022-06-18T08:24:43 +0000
Search Movie:  Bear Witness (2022)
Traceback (most recent call last):
  File "C:\Users\haig233\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\haig233\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\haig233\AppData\Local\Programs\Python\Python310\Scripts\torcp.exe\__main__.py", line 7, in <module>
  File "C:\Users\haig233\AppData\Local\Programs\Python\Python310\lib\site-packages\torcp\torcp.py", line 880, in main
    processOneDirItem(cpLocation, torFolderItem)
  File "C:\Users\haig233\AppData\Local\Programs\Python\Python310\lib\site-packages\torcp\torcp.py", line 662, in processOneDirItem
    p.parse(itemName, TMDb=(ARGS.tmdb_api_key is not None))
  File "C:\Users\haig233\AppData\Local\Programs\Python\Python310\lib\site-packages\torcp\tmdbparser.py", line 97, in parse
    self.searchTMDb(self.title, self.tmdbcat,
  File "C:\Users\haig233\AppData\Local\Programs\Python\Python310\lib\site-packages\torcp\tmdbparser.py", line 359, in searchTMDb
    results = search.movies({"query": s[1], "year": str(intyear), "page": 1})
  File "C:\Users\haig233\AppData\Local\Programs\Python\Python310\lib\site-packages\tmdbv3api\objs\search.py", line 51, in movies
    return self._get_obj(self._call(self._urls["movies"], urlencode(params)))
  File "C:\Users\haig233\AppData\Local\Programs\Python\Python310\lib\site-packages\tmdbv3api\tmdb.py", line 115, in _get_obj
    raise TMDbException(result["status_message"])
tmdbv3api.exceptions.TMDbException: Invalid API key: You must be granted a valid key.
```

TMDB Key实测可用

**Comment by ccf-2012** [comment]
盲猜DNS搞乱了？所以TMDB连了不知哪里的？

**Comment by haig233** [comment]
> 盲猜DNS搞乱了？所以TMDB连了不知哪里的？

当时V群有大佬帮我转发过我的图给您，curl访问api，可以拿到正确的JSON数据，网络访问没问题
