### ISSUE TITLE
当初始文件夹名为TV等名字时会出错

### ISSUE THREAD

**Issue by dextersa** [ccf-2012/torcp#15]
我在测试 这个命令的时候会报错
tp.py ./TV/ -d ./0r0/ --move-run  --origin-name  -e all  --emby-bracket  --tv --tmdb-api-key='****' 

如果原始文件夹名改为TVA就不会报错。另：dryrun不会报错。
请在md中说明或者优化代码。

**Comment by LeiShi1313** [comment]
报错请附上报错信息

**Comment by dextersa** [comment]
`PS M:\03动画片\0r0> C:\0temp\torcp-main\tp.py ./TV/ -d ./0r0/  --origin-name  -e all  --emby-bracket  --tv --tmdb-api-key='57924a39b7803690db0ca5b4d9cc2501'
=========>>> 2022-06-29T22:58:53 +0800
Search TV: Re：从零开始的异世界生活
Found [196959]: Re：从零开始的异世界生活 新编集版
ln  M:\03动画片\0r0\TV\Re：从零开始的异世界生活 新编集版 (2020) [tmdbid=196959]\S01\01 初始的终结与结束的开始.mp4 ./0r0/TV\Re：从零开始的异世界生活 新编集版 (2020) [tmdbid=196959]\S01\01 初始的终结与结束的开始.mp4
ln  M:\03动画片\0r0\TV\Re：从零开始的异世界生活 新编集版 (2020) [tmdbid=196959]\S01\01 初始的终结与结束的开始.nfo ./0r0/TV\Re：从零开始的异世界生活 新编集版 (2020) [tmdbid=196959]\S01\01 初始的终结与结束的开始.nfo
Traceback (most recent call last):
  File "C:\0temp\torcp-main\tp.py", line 5, in <module>
    torcp.main()
    ^^^^^^^^^^^^
  File "C:\0temp\torcp-main\torcp\torcp.py", line 884, in main
    processOneDirItem(cpLocation, torFolderItem)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\0temp\torcp-main\torcp\torcp.py", line 713, in processOneDirItem
    copyTVFolderItems(mediaSrc, destFolderName, p.season, p.group,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\0temp\torcp-main\torcp\torcp.py", line 438, in copyTVFolderItems
    copyTVSeasonItems(tvitemPath, genFolder, seasonFolder, parseGroup,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\0temp\torcp-main\torcp\torcp.py", line 287, in copyTVSeasonItems
    targetCopy(tv2itemPath, seasonFolderFullPath, newTVFileName)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\0temp\torcp-main\torcp\torcp.py", line 183, in targetCopy
    hdlinkCopy(fromLoc, toLocPath, toLocFile)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\0temp\torcp-main\torcp\torcp.py", line 76, in hdlinkCopy
    os.link(fromLoc, destFile)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] 句柄无效。: 'M:\\03动画片\\0r0\\TV\\Re：从零开始的异世界生活 新编集版 (2020) [tmdbid=196959]\\S01\\01 初始的终结与结束的开始.nfo' -> './0r0/TV\\Re：从零开始的异世界生活 新编集版 (2020) [tmdbid=196959]\\S01\\01 初始的终结与结束的开始.nfo'`
